/*
 * ReportVectCells.cpp
 *
 *  Created on: Feb 8, 2011
 *      Author: Marco.Maneta
 */

#include <fstream>
#include "Report.h"

int Report::ReportVectCells(const vectCells *input, string filename, float timestep){

	ofstream fout(filename.c_str(), ios::app);
	    if(!fout.is_open()) {cout << "Cannot create or open output file " << filename << "\n"; exit(EXIT_FAILURE);}

	  UINT4 length = input->cells.size();

	  fout.seekp(0,ios::end);
	  if (!fout.tellp()) { //if file is empty include the header and calculate the number of outlets
		fout << "#Output values file generated by ECH2O" << "\n";
		fout << length + 1 << "\n";
		fout << "ReportTime" << "\n";
		for (UINT4 i = 0; i < length; i++)
			fout << "Flow at row,col: " << input->cells[i].row << "," << input->cells[i].col << "\n";
	}

	  fout << timestep << "\t";
	  for (UINT4 i = 0; i< length; i++)
		  fout << input->cells[i].val << "\t";

	  fout << "\n";

	  if(fout.is_open())
	    fout.close();

	return EXIT_SUCCESS;
}
