/*
 * ReportTimeSeries.cpp
 *
 *  Created on: Sep 22, 2010
 *      Author: Marco.Maneta
 */
#include <fstream>
#include "Report.h"

int Report::ReportTimeSeries(const grid *input, string filename, float timestep){

	ofstream fout(filename.c_str(), ios::app);
	    if(!fout.is_open()) {cout << "Cannot create or open output file " << filename << "\n"; exit(EXIT_FAILURE);}

	  UINT4 r, c;
	  UINT4 length = mask.cells.size();

	  fout.seekp(0,ios::end);
	  if (!fout.tellp()) { //if file is empty include the header
		fout << "#Output values file generated by Xhydro" << "\n";
		fout << length + 1 << "\n";
		fout << "ReportTime" << "\n";
		for (UINT4 i = 0; i < length; i++)
			fout << "point# " << mask.cells[i].dir << "\n";
	}

	  fout << timestep << "\t";
	  for (UINT4 i = 0; i< length; i++){
		  r = mask.cells[i].row;
		  c = mask.cells[i].col;

          fout << input->matrix[r][c] << "\t";
	  }
	  fout << "\n";

	  if(fout.is_open())
	    fout.close();

	return EXIT_SUCCESS;
}
